version: '3.0'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile_service
    command: '/app/docker/service/start-server.sh'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_DB_NUMBER=0
      - REDIS_DB_PREFIX=local
      - PYTHONUNBUFFERED=1
    links:
      - redis

  service_nginx:
    build:
      context: ./docker/service_nginx
    command: '/start-nginx.sh'
    ports:
      - "8000:8000"
    links:
      - service

  redis:
    build: ./docker/redis
    ports:
      - "6379:6379"

  task_runner:
    build:
      context: ./docker/task_runner
    command: 'sh /app/start-watch.sh'
    environment:
      CONTEXT_PATH: '/app/application/src/'
      ENTRY_NAME: 'app'
      ENTRY_PATH: '/app/application/src/vuejs/app.js'
      DIST_PATH: '/app/application/staticfiles/vuejs'
    volumes:
      - .:/app/application
    ports:
      - "9000:3000"